version: 0.0
os: linux 

files:
  - source: / # 將整個專案複製到 EC2 上的這個目錄
    destination: /home/ec2-user/app/ 

hooks:
  # 部署開始前：停止舊服務
  BeforeInstall:
    - location: scripts/stop_server.sh 
      timeout: 60
      runas: root

  # 檔案複製完成後：安裝 Nginx、Node.js 相依套件、編譯 React
  AfterInstall:
    - location: scripts/install_environment.sh # 新增：安裝 Nginx 和 Node.js
      timeout: 300
      runas: root

    - location: scripts/install_dependencies.sh # Node/React 相依套件安裝與編譯
      timeout: 600 # 給予更長時間進行 npm install 和 build
      runas: ec2-user # 建議以非 root 使用者執行 npm install

    - location: scripts/build_and_copy.sh
      timeout: 300
      runas: root

  # 服務啟動後：啟動 Node.js 後端和 Nginx
  ApplicationStart:
    - location: scripts/start_server.sh 
      timeout: 120
      runas: root

  # 部署驗證：檢查 Nginx 和 Node.js 服務是否成功啟動
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: root
