version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      # 1. 建置前端
      - echo "Building React frontend..."
      - cd frontend
      - npm install
      - npm run build
      - cd .. # 回到根目錄
      
      # 2. (可選) 安裝後端依賴 (如果您的 scripts 需要)
      - echo "Installing backend dependencies..."
      - cd backend
      - npm install
      - cd .. # 回到根目錄

artifacts:
  # 3. 關鍵：只打包部署需要的檔案
  files:
    - 'frontend/dist/**/*'   # 打包建置好的前端
    - 'backend/**/*'         # 打包後端程式碼 (包含 node_modules)
    - 'appspec.yml'          # 告訴 CodeDeploy 該做什麼
    - 'scripts/*'            # 打包部署腳本
  base-directory: .